#!/usr/bin/env python3
"""
Fish Forecast — Calendar Sync (Phase 4)
========================================
Reads today's grade from daily-log.json and creates/updates
a "🎣 Fish Forecast" all-day event in Google Calendar.

Setup:
  1. pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
  2. Create a Google Cloud project, enable Calendar API
  3. Download credentials.json to this directory
  4. Run once interactively to authorize: python calendar_sync.py --auth
  5. Schedule daily with cron or pair with scheduler.js

Cron example (runs after scheduler at 6:05 AM):
  5 6 * * * cd /path/to/fish-forecast && python calendar_sync.py
"""

import json
import os
import sys
import argparse
from datetime import date, datetime

try:
    from googleapiclient.discovery import build
    from google.oauth2.credentials  import Credentials
    from google_auth_oauthlib.flow  import InstalledAppFlow
    from google.auth.transport.requests import Request
    GOOGLE_AVAILABLE = True
except ImportError:
    GOOGLE_AVAILABLE = False

SCOPES      = ['https://www.googleapis.com/auth/calendar.events']
LOG_FILE    = os.path.join(os.path.dirname(__file__), 'daily-log.json')
TOKEN_FILE  = os.path.join(os.path.dirname(__file__), 'token.json')
CREDS_FILE  = os.path.join(os.path.dirname(__file__), 'credentials.json')
CALENDAR_ID = os.environ.get('CALENDAR_ID', 'primary')

GRADE_EMOJI = {'A': '🟢', 'B': '🔵', 'C': '🟡', 'D': '🟠', 'F': '🔴'}
GRADE_LABEL = {
    'A': 'Outstanding — Get out there!',
    'B': 'Good Conditions',
    'C': 'Fair — Worth a try',
    'D': 'Poor Conditions',
    'F': 'Stay Home Today',
}

def get_credentials():
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CREDS_FILE):
                print("ERROR: credentials.json not found.")
                print("Download from Google Cloud Console > APIs > Credentials > OAuth 2.0")
                sys.exit(1)
            flow  = InstalledAppFlow.from_client_secrets_file(CREDS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, 'w') as f:
            f.write(creds.to_json())
    return creds

def load_todays_grade():
    if not os.path.exists(LOG_FILE):
        print(f"ERROR: {LOG_FILE} not found. Run the scheduler first.")
        sys.exit(1)
    with open(LOG_FILE) as f:
        log = json.load(f)
    today_str = date.today().isoformat()
    for entry in log.get('entries', []):
        if entry.get('date') == today_str:
            return entry
    if log.get('entries'):
        print(f"Warning: No entry for {today_str}, using most recent: {log['entries'][0]['date']}")
        return log['entries'][0]
    print("ERROR: daily-log.json has no entries. Run the scheduler first.")
    sys.exit(1)

def build_event(entry):
    g     = entry['grade']
    score = entry['score']
    emoji = GRADE_EMOJI.get(g, '🎣')
    label = GRADE_LABEL.get(g, '')
    today = entry.get('date', date.today().isoformat())

    description = "\n".join([
        f"Grade: {g}  |  Score: {score}/100",
        f"Status: {label}",
        "",
        "Condition Breakdown:",
        f"  Avg Temp        : {entry.get('avgTempF', '?')}F",
        f"  Avg Wind        : {entry.get('avgWindMph', '?')} mph",
        f"  Precipitation   : {entry.get('precipIn', '?')}\"",
        f"  Cloud Cover     : {entry.get('cloudPct', '?')}%",
        f"  Moon Phase      : {entry.get('moonPhase', '?')}",
        f"  Pressure Delta  : {entry.get('pressureDelta', '?')} hPa",
        "",
        "Generated by Fish Forecast",
    ])

    return {
        'summary'    : f"{emoji} Fish Forecast: {g} ({score}/100) — {label}",
        'description': description,
        'start'      : {'date': today},
        'end'        : {'date': today},
        'colorId'    : {'A': '2', 'B': '9', 'C': '5', 'D': '6', 'F': '11'}.get(g, '1'),
        'reminders'  : {
            'useDefault': False,
            'overrides' : [{'method': 'popup', 'minutes': 0}]
        },
    }

def find_existing_event(service, today_str):
    events = service.events().list(
        calendarId   = CALENDAR_ID,
        timeMin      = today_str + 'T00:00:00Z',
        timeMax      = today_str + 'T23:59:59Z',
        singleEvents = True,
        q            = 'Fish Forecast',
    ).execute()
    items = events.get('items', [])
    return items[0] if items else None

def sync_to_calendar(dry_run=False):
    print(f"\n🎣 Fish Forecast Calendar Sync — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    entry = load_todays_grade()
    g     = entry['grade']
    score = entry['score']
    print(f"   Today's grade: {g} ({score}/100) for {entry['date']}")

    if dry_run:
        event = build_event(entry)
        print("\n[DRY RUN] Would create/update event:")
        print(f"  Title : {event['summary']}")
        print(f"  Date  : {event['start']['date']}")
        print(f"  Color : {event['colorId']}")
        return

    if not GOOGLE_AVAILABLE:
        print("ERROR: Google API libraries not installed.")
        print("Run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib")
        sys.exit(1)

    creds    = get_credentials()
    service  = build('calendar', 'v3', credentials=creds)
    event    = build_event(entry)
    existing = find_existing_event(service, entry['date'])

    if existing:
        updated = service.events().update(
            calendarId=CALENDAR_ID, eventId=existing['id'], body=event
        ).execute()
        print(f"   Updated existing event: {updated.get('htmlLink')}")
    else:
        created = service.events().insert(
            calendarId=CALENDAR_ID, body=event
        ).execute()
        print(f"   Created new event: {created.get('htmlLink')}")

def main():
    parser = argparse.ArgumentParser(description='Fish Forecast -> Google Calendar Sync')
    parser.add_argument('--dry-run', action='store_true', help='Preview without writing')
    parser.add_argument('--auth',    action='store_true', help='Force re-authentication')
    args = parser.parse_args()

    if args.auth and os.path.exists(TOKEN_FILE):
        os.remove(TOKEN_FILE)
        print("Removed cached token. Re-authenticating...")

    sync_to_calendar(dry_run=args.dry_run)

if __name__ == '__main__':
    main()
